[integration/sql] Adding additional clarification in sql integration README
OpenLineage/OpenLineage pull request #1360
Opened 2022-12-02 00:20 UTC by howardyoo

Signed-off-by: howardyoo <howardyoo@gmail.com>

### Problem

The instruction mentioned in integration/sql/README.md for python language does not specify the directory the user should be in when running test and build command.

### Solution

Added additional instruction to make sure user is in the proper directory.

- [ ] Your change modifies the [core](https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.json) OpenLineage model
- [ ] Your change modifies one or more OpenLineage [facets](https://github.com/OpenLineage/OpenLineage/tree/main/spec/facets)

If you're contributing a new integration, please specify the scope of the integration and how/where it has been tested (e.g., Apache Spark integration supports `S3` and `GCS` filesystem operations, tested with AWS EMR).

### Checklist

- [x] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [x] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [ ] Your changes are accompanied by tests (_if relevant_)
- [x] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [ ] You've updated any relevant documentation (_if relevant_)
- [ ] You've updated the [`CHANGELOG.md`](https://github.com/OpenLineage/OpenLineage/blob/main/CHANGELOG.md) with details about your change under the "Unreleased" section (_if relevant, depending on the change, this may not be necessary_)
- [ ] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)
- [ ] You've added a [header](https://github.com/OpenLineage/OpenLineage/tree/main/.github/header_templates.md) to source files (_if relevant_)

----
SPDX-License-Identifier: Apache-2.0\
Copyright 2018-2022 contributors to the OpenLineage project

2022-12-02 14:28 UTC, mobuchowski requested changes

2022-12-02 14:28 UTC, mobuchowski commented on integration/sql/README.md
> +
It's right, but those lines should be after `cargo test`. You should run tests from root directory.

2022-12-02 15:21 UTC, howardyoo commented
Ok, will fix it. Thanks!

On Fri, Dec 2, 2022 at 8:28 AM Maciej Obuchowski ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In integration/sql/README.md
> <https://github.com/OpenLineage/OpenLineage/pull/1360#discussion_r1038197897>
> :
>
> > +Make sure you are in the correct directory.
> +```bash
> +cd iface-py
> +```
> +
>
> It's right, but those lines should be after cargo test. You should run
> tests from root directory.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenLineage/OpenLineage/pull/1360#pullrequestreview-1202582139>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHZNLLT5G5TOADUU6ZMFKUDWLIBRZANCNFSM6AAAAAASRLLRJM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-05 09:42 UTC, mobuchowski approved these changes

2022-12-05 09:42 UTC, merged