airflow: add Airflow composite and processing engine facets. Generate UUID for each task instance.
OpenLineage/OpenLineage pull request #1413
Opened 2022-12-12 23:29 UTC by JDarDagran

Add ProcessingEngineVersionRunFacet spec.
Add new facets to Python client.
Implement new facets in utils and adapter.
Generate UUID for each task instance.
Add task group information (Airflow > 2.3.0).

Signed-off-by: Jakub Dardzinski <kuba0221@gmail.com>

Fix facets spec.

Signed-off-by: Jakub Dardzinski <kuba0221@gmail.com>

### Problem

There are too many custom Airflow-related facets. This PR creates one standarized Airflow run facet. Additionally, it creates `ProcessingEngineVersionRunFacet` and allows to create UUID for each task instance and put it into new Airflow facet.

Closes: #1185, #1076 

### Checklist

- [x] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [x] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [x] Your changes are accompanied by tests (_if relevant_)
- [x] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [ ] You've updated any relevant documentation (_if relevant_)
- [ ] You've updated the [`CHANGELOG.md`](https://github.com/OpenLineage/OpenLineage/blob/main/CHANGELOG.md) with details about your change under the "Unreleased" section (_if relevant, depending on the change, this may not be necessary_)
- [x] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)
- [x] You've added a [header](https://github.com/OpenLineage/OpenLineage/tree/main/.github/header_templates.md) to source files (_if relevant_)

----
SPDX-License-Identifier: Apache-2.0\
Copyright 2018-2022 contributors to the OpenLineage project

2022-12-13 13:57 UTC, mobuchowski approved these changes

2022-12-14 07:30 UTC, pawel-big-lebowski requested changes
Put my concerns related to spec changes in comments. 
I am open to discuss them in more details.

2022-12-14 07:30 UTC, pawel-big-lebowski commented on spec/facets/ProcessingEngineVersionRunFacet.json
> +    "ProcessingEngineVersionRunFacet": {
Woulndn't `ProcessingEngineRunFacet` be enough?

2022-12-14 07:30 UTC, pawel-big-lebowski commented on spec/facets/ProcessingEngineVersionRunFacet.json
> +            "engine_version": {
Consider using `name` and `version` instead of `engine_version`, `engine_name`.

2022-12-14 07:30 UTC, pawel-big-lebowski commented on spec/facets/ProcessingEngineVersionRunFacet.json
> +            "engine_name": {
I think it's not stated explicitly, but in specs we do use camel case convention. That's what I observed at least.

2022-12-14 07:30 UTC, pawel-big-lebowski commented on spec/facets/AirflowRunFacet.json
> +    "AirflowRunFacet": {
If this is an Airflow specific facet, why do we want to add it into global `spec`? 

When accepting such an exception, we can end up with dbt, spark, airflow, flink, snowflake, databricks, ... facets that blur the main goal of Openlineage which is: `whatever you do with data, OL event contains a technology agnostic description of that`.

Please consider replacing this with `RunParameterFacet` or some generic way to describe run details

2022-12-16 12:33 UTC, pawel-big-lebowski approved these changes
Great effort to make things consistent 🚀  💯 🥇

2022-12-17 09:26 UTC, merged