update SPDX license headers in source code
OpenLineage/OpenLineage pull request #1468
Opened 2023-01-05 21:38 UTC by merobi-hub

Signed-off-by: Michael Robinson <merobi@gmail.com>

### Problem

The SPDX license headers, which we added last year, are out of date now that it's 2023. So they need updating to be current.

### Solution

This will change 2022 in the headers to 2023 to keep them current.

> **Note:** All schema changes require discussion. Please [link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) for context.

- [ ] Your change modifies the [core](https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.json) OpenLineage model
- [ ] Your change modifies one or more OpenLineage [facets](https://github.com/OpenLineage/OpenLineage/tree/main/spec/facets)

If you're contributing a new integration, please specify the scope of the integration and how/where it has been tested (e.g., Apache Spark integration supports `S3` and `GCS` filesystem operations, tested with AWS EMR).

### Checklist

- [x] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [x] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [ ] Your changes are accompanied by tests (_if relevant_)
- [x] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [ ] You've updated any relevant documentation (_if relevant_)
- [ ] You've updated the [`CHANGELOG.md`](https://github.com/OpenLineage/OpenLineage/blob/main/CHANGELOG.md) with details about your change under the "Unreleased" section (_if relevant, depending on the change, this may not be necessary_)
- [ ] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)
- [ ] You've added a [header](https://github.com/OpenLineage/OpenLineage/tree/main/.github/header_templates.md) to source files (_if relevant_)

----
SPDX-License-Identifier: Apache-2.0\
Copyright 2018-2023 contributors to the OpenLineage project

2023-01-10 17:39 UTC, mobuchowski requested changes
I think this needs few changes around templates and .md files, but overall giant majority of files is fine @merobi-hub

2023-01-10 17:39 UTC, mobuchowski commented on .github/ISSUE_TEMPLATE/proposal.md
> +Copyright 2018-2023 contributors to the OpenLineage project
I don't think this should be in template?

2023-01-10 17:39 UTC, mobuchowski commented on client/python/README.md
> +Copyright 2018-2023 contributors to the OpenLineage project
I don't think we need this license identifier in .md file either

2023-01-10 17:39 UTC, mobuchowski commented on integration/spark/databricks/README.md
> +Copyright 2018-2023 contributors to the OpenLineage project
I don't think we need this here

2023-01-10 17:50 UTC, merobi-hub commented
Thanks for the feedback @mobuchowski . It's ready for another look now.

2023-01-11 14:36 UTC, mobuchowski approved these changes

2023-01-11 14:36 UTC, merged