[SPARK] Add support for window functions in ColumnLineage
OpenLineage/OpenLineage pull request #2726
Opened 2024-05-24 10:50 UTC by wenfang6

### Problem
When SQL contains window functions, it can result in missing blood relationships in the window function fields, as shown in the following columns, where blood relationships in the **rank** field are missing:

```
insert overwrite table student_rank 
select name, class, age, row_number()over(partition by class order by age desc) as rank from students;
```
explain extended this sql：

```
== Optimized Logical Plan ==
InsertIntoHiveTable `dap_dev`.`student_rank`, org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe, true, false, [name, class, age, rank]
+- Window [row_number() windowspecdefinition(class#22, age#21 DESC NULLS LAST, specifiedwindowframe(RowFrame, unboundedpreceding$(), currentrow$())) AS rank#12], [class#22], [age#21 DESC NULLS LAST]
   +- Project [name#20, class#22, age#21]
      +- HiveTableRelation [`dap_dev`.`students`, org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe, Data Cols: [id#19, name#20, age#21, class#22], Partition Cols: []]
```

Rank should rely on class and age

### Solution
For window logicalPlan, handle windowExpressions and  addDependency

2024-05-28 11:14 UTC, mobuchowski requested changes

2024-05-28 11:14 UTC, mobuchowski commented on integration/spark/spark3/src/main/java/io/openlineage/spark3/agent/lifecycle/plan/column/ExpressionDependencyCollector.java
> +      expressions.allAll(
```suggestion
      expressions.addAll(
```

2024-05-28 11:14 UTC, mobuchowski commented on integration/spark/spark3/src/main/java/io/openlineage/spark3/agent/lifecycle/plan/column/ExpressionDependencyCollector.java
> +      expressions.allAll(
@wenfang6 a typo :)

2024-05-29 12:44 UTC, wenfang6 commented on integration/spark/spark3/src/main/java/io/openlineage/spark3/agent/lifecycle/plan/column/ExpressionDependencyCollector.java
> +      expressions.allAll(
sorry, my mistake

2024-09-20 14:22 UTC, JDarDagran commented
@wenfang6 would you like to sign the commit (see the DCO) and rebase to resolve the conflicts?

2025-06-02 08:07 UTC, kacpermuda commented
@wenfang6  Would you like to re-visit this PR and fix the CI so that it can be merged?

2025-06-25 08:15 UTC, dolfinus commented
Superseded by #2901, already part of OpenLineage since 1.20.0

2025-07-30 02:34 UTC, closed without merging