[SPARK] Use Table's properties during column level lineage construction
OpenLineage/OpenLineage pull request #2855
Opened 2024-07-16 12:07 UTC by ddebowczyk92

### Problem

Closes: #2853 

### Solution

Some minor code  changes  in [PlanUtils3.java](https://github.com/OpenLineage/OpenLineage/compare/main...ddebowczyk92:cll-datasetidentifier?expand=1#diff-e81cf22f0f4afef7ac0f3267936ca97fbbd8608b3326b83a7ef62a84a975b9b7)

> **Note:** All schema changes require discussion. Please [link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) for context.

- [ ] Your change modifies the [core](https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.json) OpenLineage model
- [ ] Your change modifies one or more OpenLineage [facets](https://github.com/OpenLineage/OpenLineage/tree/main/spec/facets)

If you're contributing a new integration, please specify the scope of the integration and how/where it has been tested (e.g., Apache Spark integration supports `S3` and `GCS` filesystem operations, tested with AWS EMR).

#### One-line summary:

### Checklist

- [ ] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [ ] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [ ] Your changes are accompanied by tests (_if relevant_)
- [ ] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [ ] You've updated any relevant documentation (_if relevant_)
- [ ] Your comment includes a one-liner for the changelog about the specific purpose of the change (_not required for changes to tests, docs, or CI config_)
- [ ] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)
- [ ] You've added a [header](https://github.com/OpenLineage/OpenLineage/tree/main/.github/header_templates.md) to source files (_if relevant_)

----
SPDX-License-Identifier: Apache-2.0\
Copyright 2018-2024 contributors to the OpenLineage project

2024-07-16 12:42 UTC, mobuchowski requested changes
Any test for that change?

2024-07-16 12:42 UTC, mobuchowski commented on integration/spark/spark3/src/main/java/io/openlineage/spark3/agent/utils/PlanUtils3.java
> +              if (ExtesionDataSourceV2Utils.hasExtensionLineage(relation)) {
`Extesion` -> `Extension`

2024-07-18 18:22 UTC, ddebowczyk92 commented on integration/spark/spark3/src/main/java/io/openlineage/spark3/agent/utils/PlanUtils3.java
> +  public static Optional<DatasetIdentifier> getDatasetIdentifierExtended(
@pawel-big-lebowski done :saluting_face:

2024-07-19 07:28 UTC, pawel-big-lebowski approved these changes

2024-07-19 07:31 UTC, merged