[Integration][DBT] Support for CLL in DBT integration
OpenLineage/OpenLineage pull request #3261
Opened 2024-11-19 16:32 UTC by mayurmadnani

### Problem

DBT integration does not have CLL support

Closes: #3260 

### Solution

DBT gives table level lineage in manifest. Using the SQL parser and dbt compiled code, CLL is generated.

#### One-line summary:

Adds CLL support using openlineage SQL parser to derive column lineage

### Checklist

- [x] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [x] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [ ] Your changes are accompanied by tests (_if relevant_)
- [x] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [ ] You've updated any relevant documentation (_if relevant_)
- [x] Your comment includes a one-liner for the changelog about the specific purpose of the change (_not required for changes to tests, docs, or CI config_)
- [x] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)
- [ ] You've added a [header](https://github.com/OpenLineage/OpenLineage/tree/main/.github/header_templates.md) to source files (_if relevant_)

----
SPDX-License-Identifier: Apache-2.0\
Copyright 2018-2024 contributors to the OpenLineage project

2024-11-19 17:06 UTC, mobuchowski commented
Thanks for the contribution @mayurmadnani. It would be great to add tests that check validity of the solution here. The tests are located here: https://github.com/OpenLineage/OpenLineage/tree/0399867fc3cf29015c7de1f8923b49ec0b263617/integration/common/tests/dbt

2024-11-19 19:13 UTC, mayurmadnani commented
Thanks @mobuchowski 
Added tests. Also, here is a sample run in local mode

![image](https://github.com/user-attachments/assets/d032e83f-5a79-40e5-bad3-13f54312765c)

2024-11-19 19:19 UTC, JDarDagran commented
@mayurmadnani do you have knowledge about how compiled SQL is created in results file? Do database object always stay the same in SQL statement or do they have database / schema added if they're missing in the model definition?

On the other hand, maybe this is very rare case because usually one does refer to db objects using {{ ref }}?

2024-11-19 19:28 UTC, mayurmadnani commented
> @mayurmadnani do you have knowledge about how compiled SQL is created in results file? Do database object always stay the same in SQL statement or do they have database / schema added if they're missing in the model definition?
> 
> On the other hand, maybe this is very rare case because usually one does refer to db objects using {{ ref }}?

@JDarDagran when you use {{ ref }} dbt will compile and generate the compiled SQL with db and schema info. see this- 
![image](https://github.com/user-attachments/assets/b761ac39-a5aa-4469-a506-0d7045b00274)

2024-11-19 19:31 UTC, JDarDagran commented
Is this the same for {{ source }} and tests? Sorry for being too inquisitive, just trying to make sure we don't miss some common use case.
I think your contribution is great 🚀

2024-11-19 19:47 UTC, mayurmadnani commented
> Is this the same for {{ source }} and tests? Sorry for being too inquisitive, just trying to make sure we don't miss some common use case. I think your contribution is great 🚀

Yes, holds for source and tests as well
![image](https://github.com/user-attachments/assets/e9eb2726-a581-49e4-ab23-a0d7a625b3f0)
![image](https://github.com/user-attachments/assets/e38e04f5-35f3-476c-b6f4-9138f1e13727)

2024-11-19 19:51 UTC, JDarDagran commented
Awesome, thanks for checking

2024-11-20 10:24 UTC, mobuchowski requested changes

2024-11-20 10:24 UTC, mobuchowski commented on integration/common/tests/dbt/test_dbt_local.py
> +        assert match(json.load(f), events)
@mayurmadnani there is no column-level lineage in the result event: https://github.com/OpenLineage/OpenLineage/blob/main/integration/common/tests/dbt/compiled_code/result.json

The comparison won't check existence of CLL in the event your change is generating.

2024-11-20 18:24 UTC, closed without merging