add copyright to source files
OpenLineage/OpenLineage pull request #755
Opened 2022-05-18 21:38 UTC by merobi-hub

Signed-off-by: Michael Robinson <merobi@gmail.com>

### Problem

With few exceptions, the project lacked a copyright. Including one in source files is an expectation of the LFAI.

### Solution

This PR adds copyright lines to Python, Rust, text, Markdown, Bash, and Java files throughout the project. 

- [ ] Your change modifies the [core](https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.json) OpenLineage model
- [ ] Your change modifies one or more OpenLineage [facets](https://github.com/OpenLineage/OpenLineage/tree/main/spec/facets)

If you're contributing a new integration, please specify the scope of the integration and how/where it has been tested (e.g., Apache Spark integration supports `S3` and `GCS` filesystem operations, tested with AWS EMR).

### Checklist

- [x] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [ ] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [ ] Your changes are accompanied by tests (_if relevant_)
- [x] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [ ] You've updated any relevant documentation (_if relevant_)
- [ ] You've updated the [`CHANGELOG.md`](https://github.com/OpenLineage/OpenLineage/blob/main/CHANGELOG.md) with details about your change under the "Unreleased" section (_if relevant, depending on the change, this may not be necessary_)
- [ ] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)

2022-05-30 16:35 UTC, mobuchowski commented
Can we split changes per file type, as in Marquez? https://github.com/MarquezProject/marquez/pull/1996/commits

2022-05-30 16:38 UTC, mobuchowski requested changes
In `spark` integration `bin` directory appeared, with compiled binary versions of java classes. This directory should be removed

2022-06-07 23:00 UTC, rossturk commented
> In `spark` integration `bin` directory appeared, with compiled binary versions of java classes. This directory should be removed

@mobuchowski I think this has been addressed now, do you agree?

2022-06-08 20:41 UTC, merobi-hub commented
@collado-mike, pinging you in case you have some time to review today. Thanks

2022-06-13 13:44 UTC, mobuchowski requested changes

2022-06-13 13:44 UTC, mobuchowski commented on CONTRIBUTORS.md
>  <!-- SPDX-License-Identifier: CC-BY-4.0 -->
We get double licences here, with conflicting information

2022-06-13 13:44 UTC, mobuchowski commented on CONTRIBUTORS.md
> +<!-- Copyright 2018-2022 contributors to the OpenLineage project -->
This information already is below:

`<!-- Copyright Contributors to the OpenLineage. -->`

2022-06-13 13:44 UTC, mobuchowski commented on integration/common/setup.py
> +# Copyright 2018-2022 contributors to the OpenLineage project
Any comments need to be below shebangs

` # !/usr/bin/env python`

2022-06-13 13:44 UTC, mobuchowski commented on integration/dagster/setup.py
> +# Copyright 2018-2022 contributors to the OpenLineage project
Same shebang issue here.

2022-06-13 13:44 UTC, mobuchowski commented on integration/dbt/setup.py
> +# Copyright 2018-2022 contributors to the OpenLineage project
Same shebang issue here.

2022-06-14 17:58 UTC, mobuchowski commented
I think this will work!

2022-06-16 21:00 UTC, collado-mike approved these changes
This all looks great to me!

2022-06-17 17:43 UTC, merobi-hub commented
thanks, @collado-mike . Added the lines to some files I'd missed, but now I think it's ready to be merged

2022-06-23 13:36 UTC, merobi-hub commented
All of a sudden the Spark integration tests started failing. Today I merged with main to see if that fixed the problem, but no.
Can you advise @collado-mike or @mobuchowski ? Thanks

2022-06-23 15:01 UTC, mobuchowski commented
@merobi-hub you have few duplicated files, like `integration/spark/app/src/main/java/io/openlineage/spark/agent/EventEmitter 2.java`

2022-06-23 17:01 UTC, mobuchowski approved these changes

2022-06-23 17:02 UTC, merged

2022-06-23 17:02 UTC, mobuchowski commented
@merobi-hub approved and merged

2022-06-23 20:40 UTC, merobi-hub commented
Thank you, @mobuchowski !