[INTEGRATION][AIRFLOW] Allow lineage metadata to flow through inlets and outlets
OpenLineage/OpenLineage pull request #914
Opened 2022-07-08 05:58 UTC by fenil25

Signed-off-by: Fenil Doshi <fdoshi@slack-corp.com>

### Problem

Currently, in Airflow integration, lineage is only captured via a few extractors which greatly limits its use case. Airflow allows users to manually annotate lineage for the tasks using inlets and outlets. These can be a great fallback mechanism when extractors cannot automatically extract the input and output Datasets. 
The PR closes #384 

Addresses: #384 

### Solution

Airflow sends inlets and outlets information to `LineageBackend` class. Inlets and Outlets can be one of [these](https://github.com/apache/airflow/blob/main/airflow/lineage/entities.py) entities. The code only currently supports `Table` entity because OpenLineage does not track column-level lineage yet. 
- Check the TaskMetadata object that is created after corresponding extractors extract the lineage data and see whether inputs and outputs exist
- Check whether inlets and outlets are provided for the task
- If TaskMetadata object does not have inputs/outputs, use Airflow's inlets and outlets.
- Get all the Table entities and convert them to Dataset entities that are suitable for TaskMetaData object

- [ ] Your change modifies the [core](https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.json) OpenLineage model
- [ ] Your change modifies one or more OpenLineage [facets](https://github.com/OpenLineage/OpenLineage/tree/main/spec/facets)

### Checklist

- [x] You've [signed-off](https://github.com/OpenLineage/OpenLineage/blob/main/why-the-dco.md) your work
- [x] Your pull request title follows our [guidelines](https://github.com/OpenLineage/OpenLineage/blob/main/CONTRIBUTING.md#creating-pull-requests)
- [ ] Your changes are accompanied by tests (_if relevant_)
- [x] Your change contains a [small diff](https://kurtisnusbaum.medium.com/stacked-diffs-keeping-phabricator-diffs-small-d9964f4dcfa6) and is self-contained
- [ ] You've updated any relevant documentation (_if relevant_)
- [ ] You've updated the [`CHANGELOG.md`](https://github.com/OpenLineage/OpenLineage/blob/main/CHANGELOG.md) with details about your change under the "Unreleased" section (_if relevant, depending on the change, this may not be necessary_)
- [ ] You've versioned the core OpenLineage model or facets according to [SchemaVer](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/iglu/common-architecture/schemaver) (_if relevant_)

2022-07-18 10:03 UTC, mobuchowski commented on integration/airflow/openlineage/airflow/extractors/converters.py
> +            "tags": table.tags,
Those should either be standard facets defined in OpenLineage standard, or defined somewhere custom facets.

We can do just `namespace` and `name` for now, and add this stuff later.

2022-07-18 10:47 UTC, mobuchowski requested changes
We're missing integration test, but I guess this can be added la

2022-07-20 08:44 UTC, mobuchowski approved these changes

2022-07-22 06:03 UTC, JDarDagran approved these changes

2022-07-22 11:08 UTC, merged